### ISSUE TITLE
Harmonise Marketplace Entities

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/marketplace#3]
Harmonise Solution Offers + Twins Data Models and link with [Adaptation Options](#2) and Expert Profiles Entity Types.

Data model before harmonisation:

![grafik](https://user-images.githubusercontent.com/1788226/55640089-332bd900-57cb-11e9-97b7-83ed61b17f9c.png)

**Comment by p-a-s-c-a-l** [comment]
A Solution Offer is the Expert's Product or Service advertised in the Marketplace.
A Showcase is an instance of Solution Offer, e.g. a concrete usage of a Expert Service in a specific location or a implementation / usage of a Tool or Product in a specific Location. Showcases shall be shown in the Twins Map, not Solution Offers. 

#### Question: @fgeyer16 @patrickkaleta 
 Is it possible to show two different Entity Types in the same GeoFieldMap (Twin & Showcase)?

### Changes to Solution Offer Entity Type:
- remove *Supported Scenario* as it is not clear who will define these and we cannot model all elements at risk / hazards combinations in advance. -> KISS
- instead, add Hazards, GL-Steps, Elements at Risk and Adaptation Options
- remove geofield, since this information is already part of the Expert Profile and the Showcase. A Solution offer is not applicable / limited to a single point location.
- instead, extend the Countries taxonomy by Regions (Europe, South America) or create separate Regions Taxonomy and add to this entity type (expert is able to provide the solution offer in the following regions: Europe, ...)

### Changes to Showcase Entity Type
- add Hazards, GL-Steps, Elements at Risk and Adaptation Options

Some properties needed for filtering and views are duplicated in Solution Offer and Showcase, e.g. Hazard, Element at Risk, etc.
#### Questions: @fgeyer16 @patrickkaleta 
- Is there a possibility to "inherit" properties from the Solution Offer?
- Or is it possible to pre-fill these properties when the user creates a new Showcase of a Solution Offer?

Furthermore, there are two entry points to a Showcase: Either via the Marketplace through Solution Offer -> Showcases or via the CSIS TwinsMap -> Showcase. In the later case, we would need some kind of [back reference](https://drupal.stackexchange.com/questions/247776/how-to-get-referring-items-from-a-entityreference-field-in-the-opposing-item-list) from Showcase -> Solution Offer, so that the user is able to view the related Solution Offer or Expert Profile when coming from the Twins Map as entry point.

#### Question: @fgeyer16 @patrickkaleta 
Is it possible to obtain such a back reference via the \<Paragraph\> Relation or do we have to an an additional property to the Showcase Entity Type?

**Comment by p-a-s-c-a-l** [comment]
Updated Data Model:

![grafik](https://user-images.githubusercontent.com/1788226/55814678-4f8f8480-5aef-11e9-9750-ac19d825b9fa.png)

**Comment by fgeyer16** [comment]
> Question: @fgeyer16 @patrickkaleta
> Is it possible to show two different Entity Types in the same GeoFieldMap (Twin & Showcase)?

Since you need views to create maps with multiple markers (or something else) mixing up Entity Types (node, group, group content,...) in one map is not possible. you can only show one entity type in a view. But what will work is showing multiple bundles (node type A, node type B, ...) in one map. For this the desired bundles have to use the same Geofield (field_location, or what ever).

> Questions: @fgeyer16 @patrickkaleta
> Is there a possibility to "inherit" properties from the Solution Offer?
> Or is it possible to pre-fill these properties when the user creates a new Showcase of a Solution Offer?

Inheritance is difficult because you somehow need to make a relation to on not yet existing content. Prefilling is possible by the module [Prepopulate](https://www.drupal.org/project/prepopulate). Since a link to create a new Show case would be made out of a Solution, we can add values of the solution to the query string of the link.

> Question: @fgeyer16 @patrickkaleta
> Is it possible to obtain such a back reference via the <Paragraph> Relation or do we have to an an additional property to the Showcase Entity Type?

Why the Paragraph relation? The solution offer is a group. So the Show case can be a Group content. In this case you can at least make a backreference with views by using this relation. I think we do not need a paragraph here.

Since we use Groups we really have to think what we put into content level and what into group content level. The group content makes the link between group and content and can contain own fields. E.g. Solutions are group content hazard twins are only content (as far as I understand)  So the geofield for the showing in maps should be on the content level for Solution offer. Otherwise we will not be able to show them together in one map (as I said at the beginning). Also everything what needs more than one Form display should be on content level since form modes do not work with Group content and Groups very well.

**Comment by p-a-s-c-a-l** [comment]
> For this the desired bundles have to use the same Geofield (field_location, or what ever).

ATM EntityType `Twin` uses a `field_geolocation` and `Showcase` (this is what we want to shown on the twins map) uses `location`. So we cannot show them on the same map, unless both use e.g. `field_geolocation`? What about the filtering? Is this easy to accomplish in the map with 'Bundles', e.g. show only Twins and Showcases Hazard 'Heat Wave' or EU-GL Step 'HC-LE'. I don't know if these "Bundles" (I still don't get what the OO concept behind this is (multiple inheritance subclass of entity type?). Furthermore, it seems that [bundles are not enabled](https://www.drupal.org/docs/8/modules/features/creating-and-configuring-bundles) in our Drupal instance: admin/config/development/features/bundle not found.

So it's up @patrickkaleta to decide if he can work with Bundles in one map. 

On the other hand, there a different Twins Types (property `type` currently not modelled as Taxonomy but as list of strings). We could extended the Twin Type by a reference to a Showcase and add new twin type 'Shocase' to the 'types' list. But then we would have to create an additional Twin Entity when creating a Showcase.

> Why the Paragraph relation?

I don't know. Initial design of Solution Offers data model performed by @patrickkaleta  and @DenoBeno

**Comment by fgeyer16** [comment]
OK I think we have some confusion in our wording. I will try to explain what I meant with Entity Type and Bundle with some examples

In general:
an **Entity** is the instance of 
a **bundle** is a child of 
an **Entity type**

Specific:
 the page **Learn about the Methodology** is an instance of the 
bundle **basic page** is a child of 
Entity Type **Node** 

the study **Adaptation Scenarios for Metropolitan Resilience Planning** is an instance of the
bundle **Study** is a child of
Entity type **Group**

So the bundle you linked to is not the bundle I meant. Unfortunately in Drupal things can have multiple names and word mean different things in different context.

Showcase and Twin are both bundles of the entity type Node ( or in short they are both content types) so they can be shown together in one Map. We just need to replace the field_location in the showcase by the field_geolocation of the twins (in this way we only have to "relocate" one showcase instead of many twins)
[http://cfe-zertifizierung.at/unternehmen](http://cfe-zertifizierung.at/unternehmen) shows the content type "company" (zhe markers) and the content type "geographical region" (the boundaries of the federal states) in on map

> On the other hand, there a different Twins Types (property type currently not modelled as Taxonomy but as list of strings). We could extended the Twin Type by a reference to a Showcase and add new twin type 'Showcase' to the 'types' list. But then we would have to create an additional Twin Entity when creating a Showcase.

Filtering can be easily done by every field (property) twin and showcase have (this includes the filtering by showcase or twin). So there is no need to copy a show case into a twin.

**Comment by patrickkaleta** [comment]
> 
> > Why the Paragraph relation?
> 
> I don't know. Initial design of Solution Offers data model performed by @patrickkaleta and @DenoBeno

Idea here was to give the Solution owner (= Expert) the opportunity to describe, why/how that selected showcase corresponds to the Solution offer. In reality it will probably be unlikely that a Solution offer matches a Showcase 1:1 (e.g. that showcase only implemented parts of what the Solution offer provides or the Showcase combined multiple Solution offers).

So, the paragraph (called [Solution offer reference](https://csis.myclimateservice.eu/admin/structure/paragraphs_type/solution_offer_reference)) stores one Showcase and one description field. If we decide that such a description is not necessary, then we won't need this paragraph type at all.

**Comment by p-a-s-c-a-l** [comment]
OK, I see. Then we should keep the paragraph. In Showcase I'll add an explicit reference to Solution Offers.

**Comment by patrickkaleta** [comment]
> ATM EntityType `Twin` uses a `field_geolocation` and `Showcase` (this is what we want to shown on the twins map) uses `location`. So we cannot show them on the same map, unless both use e.g. `field_geolocation`?

Yes, they both need to use the same field, so that we can display them on the same map. This is currently already the case now and both content types are displayed as expected.
<br>

> What about the filtering? Is this easy to accomplish in the map with 'Bundles', e.g. show only Twins and Showcases Hazard 'Heat Wave' or EU-GL Step 'HC-LE'. 

Your second example "filter by EU-GL step = HC-LE" could be done as a pre-filtering step. The [view](https://csis.myclimateservice.eu/admin/structure/views/view/twins) would, depending on the current step (HC, HC-LE,...), only provide those Twins/Showcases, which are intended for this particular step (user therefore cannot directly influence this via the filter options).
**For this we would need a reference field to the EU-GL taxonomy in the Twin and Showcase entities.** 

Filtering by hazards, elements at risk, Twin type, etc. could then be performed on all provided results by the user himself.
Note: This filtering will only work on fields, which are present in **both** content types Twins and Showcases (currently the case for fields: Hazards, El. at risk, but not for Twin type).

**Comment by p-a-s-c-a-l** [comment]
done
