### ISSUE TITLE
Solution Offer Column Layout

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/marketplace#4]
In Solution Offer / Manage Display **One Column** Layout is selected

![grafik](https://user-images.githubusercontent.com/1788226/56030750-e6da1f00-5d1d-11e9-9015-09d345784437.png)

The display shows actually 2 columns:

![grafik](https://user-images.githubusercontent.com/1788226/56030789-04a78400-5d1e-11e9-9954-a072c7e3f6f4.png)

Why? Where is this layout configured?

**Comment by patrickkaleta** [comment]
On that same [Manage display](https://csis.myclimateservice.eu/admin/group/types/manage/solution_offer/display) page you can set for each field an "expert" field template, where you can then add for example additional css classes to that field.
![manage-display-expert-template](https://user-images.githubusercontent.com/42167036/56035432-75549d80-5d2a-11e9-8162-68c4c3ba0cc0.png)

This was all done back in last October/November to get a "presentable" page quickly. I can remove those settings, so that we get the basic layout (as it is used on most other pages) and then (I guess?) Alejandro from Atos can at some point do the styling + layout for this.

**Comment by p-a-s-c-a-l** [comment]
OK, thanks! I would keep the custom css for now and decide later on the final styling. AFAIK SCC designers will take care.

**Comment by p-a-s-c-a-l** [comment]
Another strange problem: Title is not shown although it is configured in display: https://csis.myclimateservice.eu/group/6

![grafik](https://user-images.githubusercontent.com/1788226/56188937-04adc980-6027-11e9-8b54-f145aceee1fa.png)

And trying to move it on top fails:


![this-is-madness](https://user-images.githubusercontent.com/1788226/56189039-42125700-6027-11e9-820b-59b33b312181.gif)

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l 
Title is not shown because the settings for the [Title-Block](https://csis.myclimateservice.eu/admin/structure/block/manage/csis_page_title) have been to hide this block on URLs of the format "**/study/**" or"**/group/**"

This was done because we don't need the title in the Study groups, but I removed the second condition, since for the Studies we set the URL alias to always be **study** instead of **group**, so now the title for the Solution offer is being displayed. I think we should setup a siliar URL alias for Solution offers (e.g. /solution-offer/[Solution offer ID])

@fgeyer16 
I think you configured the autopath for the Study group. Can you tell me how to enable the same feature for Solution offers? I tried adding a similar [pattern](https://csis.myclimateservice.eu/admin/config/search/path/patterns) for the Solution offers, but it didn't work. What am I missing?

**Comment by fgeyer16** [comment]
Do you mean the 

> /study/[group:id]

pattern? 
Did you update the url-aliases for already existing nodes here:[https://csis.myclimateservice.eu/admin/config/search/path/update_bulk](https://csis.myclimateservice.eu/admin/config/search/path/update_bulk)?

**Comment by patrickkaleta** [comment]
Closing this issue. Layout for Solution offers has been changed in the new clarity theme. Issues about the styling can be created in the corresponding [repository](https://github.com/clarity-h2020/clarity-theme/issues) for the new theme.
