### ISSUE TITLE
Showcases on Twins Map

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/marketplace#8]
Showcases should be shown on the Twins Map.

**Comment by patrickkaleta** [comment]
Showcases are now shown together with Twins on the Twins map, as well as in the table below that map. Next step for me is now to implement the mechanism to include/remove Showcases (and or Twins) to the Study report.

**Comment by patrickkaleta** [comment]
Another question now is how we want to distinguish between Showcases and Twins (and possibly even Twin types?). For displaying different icons on the map, the [Geofield map module](https://www.drupal.org/project/geofield_map) provides two general options: 
- distinguish by content type: so we would get different icons for Showcases and Twins -> no need to change current data model
- or distinguish by a field (**cardinality of this field has to be 1:1, so the current fields Hazards and El. at risk won't work!**):
  - we could add a dedicated field called "icon" to both content types, so the author can set the icon directly
  - or we use the field (Twin) type to set different icons (since Showcases don't have this property yet, they would all get assigend to one default icon)

Idk if Showcases will ever have something like the `type` field in Twins. But if so, I would suggest "turning" this [type field](https://csis.myclimateservice.eu/admin/structure/types/manage/twin/fields/node.twin.field_twin_type) into a dedicated taxonomy (currently it's just a list of strings) and use it in Showcases and Twins. The overall complexity of the data structure gets increased a little, but we would gain a lot more flexibility, since it's easier to manage/update a taxnomy than a simple list of strings.

**Comment by p-a-s-c-a-l** [comment]
> distinguish by content type: so we would get different icons for Showcases and Twins -> no need to change current data model

**Following KISS and YAGNI, I would first go for this option and consider the other options later, if needed.**

>   we could add a dedicated field called "icon" to both content types, so the author can set the icon directly

Then we would have to offer a list of icons the user an choose from. (probably implemented as taxonomy :-)

> or we use the field (Twin) type to set different icons 
> I would suggest "turning" this type field into a dedicated taxonomy (currently it's just a list of strings) and use it in Showcases and Twins

Twins and Solution Offers do not share common types taxonomy, so this taxonomy would be semantically incoherent. Furthermore, there is no *type* field in the Showcase entity but in the in the Solution Offer entity. I would keep it as it is and wait for end user feedback before making further changes.

**Comment by p-a-s-c-a-l** [comment]
As we cannot wait for the outcome of [this discussion](https://github.com/clarity-h2020/docker-drupal/issues/55#issuecomment-483602032) I added a hidden field *twins_type* to the showcases entity which defaults to 'Showcase' just for the sake of showing different map icons:

![grafik](https://user-images.githubusercontent.com/1788226/57782112-d6a5cd00-772b-11e9-90b9-4f9c5b8a1dc6.png)
